
home_form:
  title: "Interaction d'§c§lOP"
  label: "Administrez les îles"
  leader: "Changer de propriétaire"
  teleport: "Se téléporter à une ile"
  delete: "Supprimer une ile"
  tiers: "Gestion du niveau"

search_form:
  title: "Chercher un propriétaire d'île"
  title_select: "Selectioner une île"
  start_with: "Qui commence par"
  start_with_placeholder: "Xx_PlayerDuRPG011013Zzz_Xx"
  message_founds: "Il y a {COUNT} propriétaires d'îles qui commencent par {START_WITH}"
  message_error: "§cIl n'y a pas de propriétaire d'île commençant par §f{START_WITH}§c."

leader_form:
  title: "Gestion de propriété"
  label: "§cSi§f l'ile §c{ISLAND_ID} §fest chargée, une fois les modifications appliquées, les membres seront déconnectés, et l'île sera déchargée."
  new_owner: "Nouveau propriétaire"
  new_rank: "Nouveau grade à l'ancien propriétaire"
  message_new_owner: "Le propriétaire de l'île est passé à §f{NEW_OWNER}§a. (ancien propriétaire: §f{OLD_OWNER}§a)"
  message_success: "Vous avez changé le propriétaire de l'île §f{ISLAND_ID} §aà §f{NEW_OWNER}§a, le message de changement de grade a été envoyé au §f{COUNT_PING} membres §aconnectées actuellements"

delete_form:
  title: "Suppression d'île"
  message: "Êtes-vous sûr de vouloir supprimer l'île §f{ISLAND_ID}§a ? cette action est §cirréversible§f!"
  yes: "Oui"
  no: "Non"

tiers_form:
  title: "Gérer le niveau"
  label: "Tiers disponibles:"
  label_line: "\n- ({TIER_ID}) {TIER_NAME}: {BLOCKS} blocs à casser"

# Choose gamemode
teleport_mode: "creative" # survival, creative, adventure, spectator