
home_form:
  leader: "Changer de propriétaire"
  teleport: "Se téléporter à une ile"
  delete: "Supprimer une ile"
  tiers: "Gestion du niveau"

leader_form:
  title: "Gestion de propriété"
  label: "§cSi§f l'ile §c{ISLAND_ID} §fest chargée, une fois les modifications appliquées, les membres seront déconnectés, et l'île sera déchargée."
  new_owner: "Nouveau propriétaire"